on: pull_request

jobs:
  dependabot:
    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - id: metadata
        name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1

      - if: ${{ steps.metadata.outputs.dependency-type == 'direct:production' }}
        name: Merge Dependabot PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
